name: Build and Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string
      generate_translations:
        description: 'Generate translations before build?'
        required: false
        default: 'false'
        type: boolean
        
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            node-version: 20.x
            build-command: npm run build:win
            cache-key: win
          - os: macos-latest
            node-version: 20.x
            build-command: npm run build:mac
            cache-key: mac
          - os: ubuntu-latest
            node-version: 20.x
            build-command: npm run build:linux
            cache-key: linux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -qq
        sudo apt-get install --no-install-recommends -y libopenjp2-tools
    
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit --no-fund --silent --ignore-scripts

    - name: Generate translations
      if: ${{ github.event.inputs.generate_translations == 'true' }}
      run: npm run generate-translations ${{ secrets.GEMINI_API_KEY }}
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    
    - name: Commit generated translations
      if: ${{ github.event.inputs.generate_translations == 'true' }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/renderer/src/translations/languages/*.ts
        git diff --staged --quiet || git commit -m "Update translations for v${{ github.event.inputs.version }}"
    
    - name: Push changes
      if: ${{ github.event.inputs.generate_translations == 'true' }}
      run: git push

    - name: Build app
      run: ${{ matrix.build-command }}
      env:
        NODE_OPTIONS: --max-old-space-size=4096
        VITE_DB_URL: ${{ secrets.DB_URL }}
        VITE_DB_KEY: ${{ secrets.DB_KEY }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_URL }}
        MAIN_VITE_API_KEY: ${{ secrets.API_KEY }}
        MAIN_VITE_LOCAL_API_KEY: ${{ secrets.LOCAL_API_KEY }}

    - name: Compress artifacts
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          7z a -tzip build-artifacts.zip dist/*.exe dist/*.msi dist/latest.yml 2>/dev/null || true
        elif [ "$RUNNER_OS" == "macOS" ]; then
          zip -r build-artifacts.zip dist/*.dmg dist/*.zip dist/latest.yml 2>/dev/null || true
        else
          zip -r build-artifacts.zip dist/*.AppImage dist/*.deb dist/*.rpm dist/latest.yml 2>/dev/null || true
        fi
      shell: bash
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.cache-key }}
        path: build-artifacts.zip
        retention-days: 1
        compression-level: 1

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get commit messages since last tag
      id: changelog
      run: |
        REPO_URL="https://github.com/${{ github.repository }}"
        LAST_TAG=$(git describe --tags --abbrev=0 || echo "")
        echo "Last tag: $LAST_TAG"

        if [ -z "$LAST_TAG" ]; then
          LOG_RANGE="HEAD"
        else
          LOG_RANGE="$LAST_TAG..HEAD"
        fi

        COMMITS=$(git log $LOG_RANGE -n 50 --pretty=format:"- [\`%h\`]($REPO_URL/commit/%H) %s (%an)")
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$COMMITS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Extract and organize artifacts
      run: |
        mkdir -p release-files
        cd artifacts
        for dir in */; do
          if [ -f "$dir/build-artifacts.zip" ]; then
            unzip -q "$dir/build-artifacts.zip" -d "../release-files/"
          fi
        done
        cd ..
        ls -la release-files/

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Dione v${{ github.event.inputs.version }}
        files: release-files/**
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
